version: '4'
services:
  postgres:
    image: postgres:15-alpine
    container_name: psg01
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432", "-U", "dev-user", "-d", "dev_db"]
      interval: 10s
      retries: 3
    networks:
      - TrigifyTest
    # Uncomment to persist database
    #    volumes:
    #      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    # Uncomment to persist database
#    volumes:
#      - app-data:/app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    command:  python main.py --watch 'imports'
    networks:
      - TrigifyTest

networks:
    TrigifyTest:
# Uncomment to persist database
#volumes:
#  postgres-data:
#  app-data